name: Lint

on:
  push:
  pull_request:

jobs:
  buildifier:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: sudo wget https://github.com/bazelbuild/buildtools/releases/latest/download/buildifier-linux-amd64 -O /usr/local/bin/buildifier
      - run: sudo chmod +x /usr/local/bin/buildifier

      - run: buildifier -lint warn -r .
